"""employer roles and permission changed to better suit the current scope

Revision ID: 20c2a4cac47b
Revises: b4e8f1a2c9d0
Create Date: 2026-08-24 23:25:04.331314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c2a4cac47b'
down_revision: Union[str, Sequence[str], None] = 'b4e8f1a2c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_employer_profiles_invitation_token'), table_name='employer_profiles', postgresql_where='(invitation_token IS NOT NULL)')
    op.drop_index(op.f('uq_employer_profiles_org_email'), table_name='employer_profiles', postgresql_where='(email IS NOT NULL)')
    op.create_unique_constraint('uq_employer_profiles_org_email', 'employer_profiles', ['organization_id', 'email'])
    op.create_unique_constraint(None, 'employer_profiles', ['invitation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employer_profiles', type_='unique')
    op.drop_constraint('uq_employer_profiles_org_email', 'employer_profiles', type_='unique')
    op.create_index(op.f('uq_employer_profiles_org_email'), 'employer_profiles', ['organization_id', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('uq_employer_profiles_invitation_token'), 'employer_profiles', ['invitation_token'], unique=True, postgresql_where='(invitation_token IS NOT NULL)')
    # ### end Alembic commands ###
