"""Initial migration based on current schema

Revision ID: 21f926bc9796
Revises: 4daed6413fe8
Create Date: 2026-01-13 13:13:01.390404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f926bc9796'
down_revision: Union[str, Sequence[str], None] = '4daed6413fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admin_sessions_jti'), table_name='platform_admin_sessions')
    op.create_index('ix_platform_admin_sessions_jti', 'platform_admin_sessions', ['jti'], unique=False)
    op.drop_column('users', 'is_profile_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_profile_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_platform_admin_sessions_jti', table_name='platform_admin_sessions')
    op.create_index(op.f('ix_platform_admin_sessions_jti'), 'platform_admin_sessions', ['jti'], unique=True)
    # ### end Alembic commands ###
