"""make default list instead of [] in job collaborator ids schema

Revision ID: 48d0a2a78a16
Revises: 21f926bc9796
Create Date: 2026-02-21 12:34:27.836388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d0a2a78a16'
down_revision: Union[str, Sequence[str], None] = '21f926bc9796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admin_sessions_jti'), table_name='platform_admin_sessions')
    op.create_index(op.f('ix_platform_admin_sessions_jti'), 'platform_admin_sessions', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admin_sessions_jti'), table_name='platform_admin_sessions')
    op.create_index(op.f('ix_platform_admin_sessions_jti'), 'platform_admin_sessions', ['jti'], unique=False)
    # ### end Alembic commands ###
