"""change application status offered to offer

Revision ID: 579916f7ad74
Revises: 742607f46467
Create Date: 2026-06-14 03:35:11.273256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579916f7ad74'
down_revision: Union[str, Sequence[str], None] = '742607f46467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.create_index('ix_user_sessions_jti', 'user_sessions', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_jti', table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=False)
    # ### end Alembic commands ###
