"""added the saved jobs table

Revision ID: 742607f46467
Revises: d6d22843084e
Create Date: 2026-03-18 12:23:22.628486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742607f46467'
down_revision: Union[str, Sequence[str], None] = 'd6d22843084e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_jobs_candidate_id', 'saved_jobs', ['candidate_id'], unique=False)
    op.create_index('ix_saved_jobs_job_candidate_unique', 'saved_jobs', ['job_id', 'candidate_id'], unique=True)
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.create_index('ix_platform_admins_email', 'platform_admins', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platform_admins_email', table_name='platform_admins')
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.drop_index('ix_saved_jobs_job_candidate_unique', table_name='saved_jobs')
    op.drop_index('ix_saved_jobs_candidate_id', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
