"""change application status offered to offer

Revision ID: d0c09863c9b4
Revises: 579916f7ad74
Create Date: 2026-06-14 03:38:46.836394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c09863c9b4'
down_revision: Union[str, Sequence[str], None] = '579916f7ad74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admin_sessions_jti'), table_name='platform_admin_sessions')
    op.create_index('ix_platform_admin_sessions_jti', 'platform_admin_sessions', ['jti'], unique=False)
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.create_index('ix_platform_admins_email', 'platform_admins', ['email'], unique=False)
    op.execute("""
        ALTER TYPE applicationstatus
        RENAME VALUE 'HIRED' TO 'OFFER';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platform_admins_email', table_name='platform_admins')
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.drop_index('ix_platform_admin_sessions_jti', table_name='platform_admin_sessions')
    op.create_index(op.f('ix_platform_admin_sessions_jti'), 'platform_admin_sessions', ['jti'], unique=True)
    op.execute("""
        ALTER TYPE applicationstatus
        RENAME VALUE 'OFFER' TO 'HIRED';
    """)
    # ### end Alembic commands ###
