"""make default list instead of [] in job collaborator ids schema

Revision ID: d6d22843084e
Revises: 48d0a2a78a16
Create Date: 2026-02-24 17:22:37.378521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d22843084e'
down_revision: Union[str, Sequence[str], None] = '48d0a2a78a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("jobs", "collaborator_employer_ids")

    op.add_column(
        "jobs",
        sa.Column(
            "collaborator_employer_ids",
            postgresql.ARRAY(sa.UUID(as_uuid=True)),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_jti', table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.drop_index('ix_platform_admin_sessions_jti', table_name='platform_admin_sessions')
    op.create_index(op.f('ix_platform_admin_sessions_jti'), 'platform_admin_sessions', ['jti'], unique=True)
    op.alter_column('jobs', 'collaborator_employer_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
