"""employer roles and permission changed to better suit the current scope

Revision ID: e28585946be2
Revises: 8f3c1a9b2d47
Create Date: 2026-08-24 15:18:46.702091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e28585946be2"
down_revision: Union[str, Sequence[str], None] = "8f3c1a9b2d47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("invited_by_employer_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "RECRUITER",
                "INTERVIEWER",
                name="teammemberrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INVITED",
                "ACTIVE",
                "REJECTED",
                "DISABLED",
                name="teammemberstatus",
            ),
            nullable=False,
        ),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("invitation_token", sa.String(length=255), nullable=True),
        sa.Column(
            "invitation_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "rejected_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_employer_id"],
            ["employer_profiles.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invitation_token"),
    )

    op.create_index(
        "ix_organization_members_email",
        "organization_members",
        ["email"],
        unique=False,
    )

    op.create_index(
        "ix_organization_members_organization_id",
        "organization_members",
        ["organization_id"],
        unique=False,
    )

    op.create_index(
        "ix_organization_members_role",
        "organization_members",
        ["role"],
        unique=False,
    )

    op.create_index(
        "ix_organization_members_status",
        "organization_members",
        ["status"],
        unique=False,
    )

    op.drop_index(
        op.f("ix_platform_admin_sessions_jti"),
        table_name="platform_admin_sessions",
    )

    op.create_index(
        op.f("ix_platform_admin_sessions_jti"),
        "platform_admin_sessions",
        ["jti"],
        unique=True,
    )

    op.drop_index(
        op.f("ix_platform_admins_email"),
        table_name="platform_admins",
    )

    op.create_index(
        op.f("ix_platform_admins_email"),
        "platform_admins",
        ["email"],
        unique=True,
    )

    # The old `role` enum and the new `usertype` enum contain
    # the same values (CANDIDATE, EMPLOYER).
    #
    # PostgreSQL cannot automatically cast between two different
    # enum types, so explicitly cast through text.
    op.execute(
        """
        ALTER TABLE user_roles
        ALTER COLUMN role TYPE usertype
        USING role::text::usertype
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Convert user_roles.role back from usertype to the old role enum.
    op.execute(
        """
        ALTER TABLE user_roles
        ALTER COLUMN role TYPE role
        USING role::text::role
        """
    )

    op.drop_index(
        op.f("ix_platform_admins_email"),
        table_name="platform_admins",
    )

    op.create_index(
        op.f("ix_platform_admins_email"),
        "platform_admins",
        ["email"],
        unique=False,
    )

    op.drop_index(
        op.f("ix_platform_admin_sessions_jti"),
        table_name="platform_admin_sessions",
    )

    op.create_index(
        op.f("ix_platform_admin_sessions_jti"),
        "platform_admin_sessions",
        ["jti"],
        unique=False,
    )

    op.drop_index(
        "ix_organization_members_status",
        table_name="organization_members",
    )

    op.drop_index(
        "ix_organization_members_role",
        table_name="organization_members",
    )

    op.drop_index(
        "ix_organization_members_organization_id",
        table_name="organization_members",
    )

    op.drop_index(
        "ix_organization_members_email",
        table_name="organization_members",
    )

    op.drop_table("organization_members")

    # ### end Alembic commands ###